/**
 * This is an autogenerated file. Do not EDIT.
 * All changes made to this file will be lost.
 * See mainboard's cmos.layout file.
 */

#ifndef __OPTION_TABLE_H
#define __OPTION_TABLE_H

#define CMOS_VSTART_reserved_memory	0
#define CMOS_VLEN_reserved_memory	384
#define CMOS_VSTART_boot_option	384
#define CMOS_VLEN_boot_option	1
#define CMOS_VSTART_reboot_counter	388
#define CMOS_VLEN_reboot_counter	4
#define CMOS_VSTART_hw_scrubber	395
#define CMOS_VLEN_hw_scrubber	1
#define CMOS_VSTART_interleave_chip_selects	396
#define CMOS_VLEN_interleave_chip_selects	1
#define CMOS_VSTART_max_mem_clock	397
#define CMOS_VLEN_max_mem_clock	2
#define CMOS_VSTART_multi_core	399
#define CMOS_VLEN_multi_core	1
#define CMOS_VSTART_power_on_after_fail	400
#define CMOS_VLEN_power_on_after_fail	1
#define CMOS_VSTART_debug_level	412
#define CMOS_VLEN_debug_level	4
#define CMOS_VSTART_slow_cpu	440
#define CMOS_VLEN_slow_cpu	4
#define CMOS_VSTART_nmi	444
#define CMOS_VLEN_nmi	1
#define CMOS_VSTART_iommu	445
#define CMOS_VLEN_iommu	1
#define CMOS_VSTART_user_data	728
#define CMOS_VLEN_user_data	256
#define CMOS_VSTART_check_sum	984
#define CMOS_VLEN_check_sum	16
#define CMOS_VSTART_amd_reserved	1000
#define CMOS_VLEN_amd_reserved	24

#define LB_CKS_RANGE_START 49
#define LB_CKS_RANGE_END 122
#define LB_CKS_LOC 123

#endif /* __OPTION_TABLE_H */
