/**
 * This is an autogenerated file. Do not EDIT.
 * All changes made to this file will be lost.
 * See mainboard's cmos.layout file.
 */

#ifndef __OPTION_TABLE_H
#define __OPTION_TABLE_H

#define CMOS_VSTART_reserved_memory	0
#define CMOS_VLEN_reserved_memory	384
#define CMOS_VSTART_boot_option	384
#define CMOS_VLEN_boot_option	1
#define CMOS_VSTART_reboot_counter	388
#define CMOS_VLEN_reboot_counter	4
#define CMOS_VSTART_debug_level	412
#define CMOS_VLEN_debug_level	4
#define CMOS_VSTART_boot_first	416
#define CMOS_VLEN_boot_first	4
#define CMOS_VSTART_boot_second	420
#define CMOS_VLEN_boot_second	4
#define CMOS_VSTART_boot_third	424
#define CMOS_VLEN_boot_third	4
#define CMOS_VSTART_boot_index	428
#define CMOS_VLEN_boot_index	4
#define CMOS_VSTART_boot_countdown	432
#define CMOS_VLEN_boot_countdown	8
#define CMOS_VSTART_sata_mode	440
#define CMOS_VLEN_sata_mode	8
#define CMOS_VSTART_sata_speed	448
#define CMOS_VLEN_sata_speed	8
#define CMOS_VSTART_check_sum	984
#define CMOS_VLEN_check_sum	16
#define CMOS_VSTART_amd_reserved	1000
#define CMOS_VLEN_amd_reserved	24

#define LB_CKS_RANGE_START 49
#define LB_CKS_RANGE_END 56
#define LB_CKS_LOC 123

#endif /* __OPTION_TABLE_H */
